#!/usr/bin/expect -f
set timeout -1
spawn sudo /usr/bin/vpn -f
expect "*murali:*"
send -- "\r"

expect "done! reconnect? (y/N): "
send -- "y\r"


expect "Username:"
send -- "ramachandra-muralidh\r"

expect "Password:"
send -- "\r"

expect "...giving up, delete cookie and try again? (Y/n) "
send -- "Y\r"

expect "Username:"
send -- "ramachandra-muralidh\r"

expect "Password:"
send -- "\r"

expect eof 
