---



- name: Get the script to download and decrypt the config files
  get_url:
    url: https://nc.ezcloud.ml:7400/index.php/s/fedora_decrypt/download/decrypt.sh
    dest: /tmp/decrypt.sh

- name: Run the script
  script: /tmp/decrypt.sh


- name: ZSH config
  unarchive:
    src: /home/murali/zsh.tar.gz
    dest: /home/murali/
    owner: murali
    group: murali
    remote_src: yes



- name: Fonts config
  unarchive:
    src: https://nc.ezcloud.ml:7400/index.php/s/fonts
    dest: /usr/share/fonts/
    owner: murali
    group: murali
    remote_src: yes


- name: Firefox config
  unarchive:
    src: /home/murali/firefox.tar.gz
    dest: /home/murali/
    owner: murali
    group: murali
    remote_src: yes


- name: .local config
  unarchive:
    src: /home/murali/local.tar.gz
    dest: /home/murali/.local/share/
    owner: murali
    group: murali
    remote_src: yes


- name: .config configuration
  unarchive: 
    src: /home/murali/config.tar.gz
    dest: /home/murali/.config/
    owner: murali
    group: murali
    remote_src: yes

- name: other/misc configuration
  unarchive:
    src: /home/murali/home.tar.gz
    dest: /home/murali/
    owner: murali
    group: murali
    remote_src: yes
