---


#- name: ZSH config
#  become: yes
#  become_method: su
#  become_user: murali
#  synchronize:
#    src: zsh/.oh-my-zsh
#    dest: /home/murali/
#
#- name: ZSH copy
#  copy:
#    src: zsh/.zsh_history
#    dest: /home/murali/
#    owner: murali
#    group: murali


- name: ZSH config
  unarchive:
    src: https://nc.ezcloud.ml:7400/index.php/s/Jf8oziSYzLFYoPN/download/zsh.tar.gz
    dest: /home/murali/
    owner: murali
    group: murali
    remote_src: yes



- name: Fonts config
  unarchive:
    src: https://nc.ezcloud.ml:7400/index.php/s/Q7WW8YaXLKNbgDg/download/fonts.tar.gz
    dest: /usr/share/fonts/
    owner: murali
    group: murali
    remote_src: yes

